name: Build Kernel (SDM710 + KSU)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout kernel
      uses: actions/checkout@v4
      with:
        repository: Rocky7842/android_kernel_xiaomi_sdm710
        ref: lineage-23.2-ksu
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison flex libssl-dev make \
          clang lld llvm

    - name: Set env
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "LLVM=1" >> $GITHUB_ENV

    - name: Build kernel
      run: |
        make sirius.config
        make -j$(nproc) Image.gz-dtb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel
        path: arch/arm64/boot/Image.gz-dtb
